info:
	cd src ; make info

all:
	cd src ; make all

loclib:
	cd src ; make loclib

loclib_only:
	cd src ; make loclib_only

ide_internal:
	cd src ; make ide_internal

ide_external:
	cd src ; make ide_external

fake_external.a:
	cd src ; make fake_external.a

example1.x:
	cd src ; make example1.x

example2.x:
	cd src ; make example2.x

example3.x:
	cd src ; make example3.x

example4.x:
	cd src ; make example4.x

iotk_copy.x:
	cd src ; make iotk_copy.x

iotk.x:
	cd src ; make iotk.x

test2.x:
	cd src ; make test2.x

test3.x:
	cd src ; make test3.x

test4.x:
	cd src ; make test4.x

test5.x:
	cd src ; make test5.x

test6.x:
	cd src ; make test6.x

test7.x:
	cd src ; make test7.x

test8.x:
	cd src ; make test8.x

test9.x:
	cd src ; make test9.x

test.x:
	cd src ; make test.x

libiotk.a:
	cd src ; make libiotk.a

libs:
	cd src ; make libs

make:
	cd src ; make make

allmake:
	cd src ; make allmake

clean_:
	cd src ; make clean_

clean:
	cd src ; make clean

tarlist:
	cd src ; make tarlist

tar:
	cd src ; make tar

alltar:
	cd src ; make alltar

update:
	cd src ; make update

update-compare:
	cd src ; make update-compare

export:
	cd src ; make export

print_info:
	cd src ; make print_info

