#
# DO NOT EDIT THIS FILE MANUALLY
# This makefile was automatically generate for IDE home directory
#
# Global OPTIONS file has been used in generation

# Main target
info:
	@echo  
	@echo  "  S3 IDE (Integrated Development Environment)"
	@echo     
	@echo  "  type:  make <target>"
	@echo  "  Possible <target>'s are: "
	@echo  "    make                 make IDE global Makefile" 
	@echo  "    allmake              make IDE Makefiles in each dir "
	@echo  "    clean                IDE total cleanup  "
	@echo  "    add                  launch a script to add a new pakage "
	@echo  "    <dir>_all            make all executable in <dir>   " 
	@echo  "    <dir>_loclib         make the local library in <dir>   " 
	@echo  "    <dir>_make           make the Makefile for <dir>   " 
	@echo  "    <dir>_allmake        make all the Makefiles for <dir> and its libs  "
	@echo  "    <dir>_clean          cleanup in <dir>  "
	@echo  "    <dir>_tar            tar of a single dir  "
	@echo  "    <dir>_alltar         tar of a dir with its libs "
	@echo    
	@echo  "  Possible <dir> values are: "     
	@echo  "    iotk  " 
	@echo   


# targets for libs handling

iotk_all: 
	cd iotk ; make all 
iotk_loclib: 
	cd iotk ; make loclib 
iotk_make: 
	IDE/makemake.sh iotk 
iotk_allmake: iotk_make 
	cd iotk ; make allmake
iotk_clean: 
	cd iotk ; make clean 
iotk_tar: 
	cd iotk ; make tar 
iotk_alltar: 
	cd iotk ; make alltar 


# make all Makefiles
allmake:  make 
	make -f Makefile allmake_
allmake_:
	IDE/makemake.sh iotk

# target for making Makefile
make: 
	IDE/IDE_makemake.sh 

# target to launch add_dir
add: 
	IDE/add_dir

# clean all
clean:  
	cd iotk ; make clean_
